### ISSUE TITLE
Roland S550 issue

### ISSUE THREAD

**Issue by chickeneps** [ZuluSCSI/ZuluSCSI-firmware#12]
Power on, the LED stays on for 10 seconds, then turns off. It takes about 30sec for the S550 to do it's SCSI check; when it starts, the LED turns on again for 20sec. The S550 does start the SCSI check but has no response and stalls the S550 forever.

Log attached.

[1326ms] Platform: ZuluSCSI v1.0
[1326ms] FW Version: 1.0.2 May 17 2022 08:12:51
[zululog_S550.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/8783007/zululog_S550.txt)

**Comment by aperezbios** [comment]
We believe this compatibility issue with the Roland S550 is fully resolved as of firmware release 1.0.7. Closing as complete.
