### ISSUE TITLE
Physical eject button for changing between CD-ROM iso images

### ISSUE THREAD

**Issue by csulaguy** [ZuluSCSI/ZuluSCSI-firmware#135]
I suppose this is more of a suggestion than an issue, but is it possible in a future revision to have a hardware pushbutton for the purpose of switching cd-rom images, and have that button tied to a specific SCSI ID in the .ini file? I know ZuluSCSI and RP2040 support multiple images, but not all OSes provide an easy way to eject a drive, since a physical drive would obviously have an eject button on it typically.

**Comment by PetteriAimonen** [comment]
On most models there is an expansion pinheader, so this could even be added to current revisions.

**Comment by csulaguy** [comment]
I presume this would be J303. How hard is it to implement this with a firmware update, so I can add this functionality? Or even the option of using that with more than one SCSI ID (if I'm emulating two or three CD-ROM drives in total)?

**Comment by aperezbios** [comment]
@csulaguy it gets much more complicated to implement for more than one removable/CD-ROM drive, because there's no real way of knowing which SCSI ID it's intended for.

**Comment by csulaguy** [comment]
I know this is an older thread, but how possible will it be to add a momentary switch to some pins on the expansion header, so I can achieve eject functionality with CD-ROMs on a given SCSI ID?

**Comment by aperezbios** [comment]
@csulaguy which ZuluSCSI model do you have? The full size V1.1, or ZuluSCSI RP2040?

**Comment by csulaguy** [comment]
> @csulaguy which ZuluSCSI model do you have? The full size V1.1, or ZuluSCSI RP2040?

Both.

**Comment by PetteriAimonen** [comment]
My suggested minimal implementation would be:

1. Support for two buttons, first one connected between SDA pin and GND, second one between SCL and GND. I think these pins are available on all current models.
2. INI file configuration like:

```
[SCSI2]
EjectButton = 1

[SCSI5]
EjectButton = 2
```

This would allow future configuration for other button functions if we invent any, or use of actual I2C devices because the buttons disturb the bus only when pressed.

**Comment by csulaguy** [comment]
Where would I find SDA/SCL and GND? On 1.1, would it be part of J305 on v1.1? And where on RP2040?

**Comment by PetteriAimonen** [comment]
On full size RP2040, the pins are labeled SDA and SCL on the bottom side of the PCB.
On RP2040 compact, it is on J305 but unlabeled.

On V1.0 and V1.1, PB8 = SCL, PB9 = SDA, though the eject button could just as well use e.g. PE5 because there are multiple pins to choose from.

But in any case, do note that the software implementation has not been done yet. @aperezbios What do you think about the suggested implementation above?

**Comment by tenox7** [comment]
I personally would love this! +1000

**Comment by aperezbios** [comment]
@PetteriAimonen I think it seems reasonable. We should probably avoid using the i2c-specific pins as general GPIOs, on platforms where we have extra usable GPIOs by default.

**Comment by PetteriAimonen** [comment]
Hmm, why the close?

**Comment by aperezbios** [comment]
Apologies, that was unintentional :)

**Comment by csulaguy** [comment]
> Apologies, that was unintentional :)

I saw that earlier and thought maybe firmware was updated for this. Definitely looking forward to this functionality in the future though. Thanks y'all for working on it!

**Comment by PetteriAimonen** [comment]
There is now a test build with support for physical eject buttons.

- Firmware for testing: https://github.com/ZuluSCSI/ZuluSCSI-firmware/actions/runs/5089734474
- Documentation: https://github.com/ZuluSCSI/ZuluSCSI-firmware/blob/8fb7380b5206ba28c3eacbf9cd4547c7406be484/README.md#physical-eject-button-for-cdrom

**Comment by nielsmh** [comment]
Oh, I was just wishing for this, I'm looking forward to trying this, when I get some time to take my RP2040 out of the machine it's in and solder on a button.

Looking over the code, it looks like it's also supported for ejecting other media types than CD? Could this work for floppies too?
And while it isn't really in my use cases (yet?), support for switching media for tapes could perhaps be useful as well.

**Comment by PetteriAimonen** [comment]
It's currently only implemented for CDs, but yes, it would make sense to expand it for other media types also.

Currently there is not yet tape / floppy switching implementation.

**Comment by ThatRed** [comment]
Hi, I tested it with button 1 on a ZuluSCSI RP2040 and can now easily change CDs while playing "Under a Killing Moon" ! Thank you!
