### ISSUE TITLE
Piezo speaker options on RP2040

### ISSUE THREAD

**Issue by csulaguy** [ZuluSCSI/ZuluSCSI-firmware#136]
I see there is an area on the PCB for an optional piezo speaker. Several questions - any suggestions on a specific part from Mouser or Digikey that could be used? And how would this be enabled in zuluscsi.ini? Can it be enabled for a particular drive (as opposed to all of them)?

**Comment by PetteriAimonen** [comment]
There is related discussion here: https://github.com/ZuluSCSI/ZuluSCSI-firmware/discussions/132

It's in parallel with the status LED, so the speaker will rattle for every access.

**Comment by aperezbios** [comment]
Please continue discussion in #132
