### ISSUE TITLE
All ZuluSCSI hard crashes when image is set on ID 7 3.14 versions

### ISSUE THREAD

**Issue by chickeneps** [ZuluSCSI/ZuluSCSI-firmware#162]
Subject says it all. Only with the RP2040 Mini boards, not any other ZuluSCSI board. 3-14-2023 firmware, and tried on several units.

Error log is attached. You can replicate by simply adding any file named ID7.img in the root.
[zuluerr.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/11034098/zuluerr.txt)

**Comment by MeTalOneOEight** [comment]
There is a similar crash on BlueScsi2 which shares the hardware and code base:
https://github.com/BlueSCSI/BlueSCSI-v2/issues/11

Maybe try changing the quirk in the zuluscsi.ini?

**Comment by chickeneps** [comment]
I tried Quirks = 1 and it still hard crashes.

**Comment by PetteriAimonen** [comment]
I have reverted the relevant commit. I had missed in code review that there was no way for this check to work at this position of the code, as the device configuration has not been loaded when we are still just searching for images.

The check could be done in ZuluSCSI_disk.cpp, but I wonder if this is even worth doing. At most, I would add a warning instead of outright forbidding the configuration. Some other host device might be usable with Apple quirks and ID 7.

**Comment by chickeneps** [comment]
Sorry to be dense but does this means it's fixed; i.e. it won't hard crash when there's a ID7 and that ID7 is accessible for storage? I just want to remind everyone that many hosts in my market do not use ID7 as the host ID, and are fixed as some other ID. Plus I don't believe it's even in the SCSI spec that 7 has to be the host ID.

**Comment by chickeneps** [comment]
Forgive my denseness (again), but how do you update the firmware on a RP2040 Mini using a uf2 file? I know how it works on a fullsize RP2040 (DIP switch BOOTLOADER), copy UF2 into the RPI volume, etc.), but the Mini doesn't have those DIP switches.

Plus I should note that on the firmware release page, there are BIN files and UF2 files but no instructions for UF2. Why make them available if there are no instructions on how to use them?

**Comment by chickeneps** [comment]
Thanks. Tried that, worked... but it disables the Mini - no LED, no log, no nothing. Was able to back-load 3.14 firmware and all is well with the board again (except the ID7 issue of course).

**Comment by aperezbios** [comment]
@chickeneps thanks, I was able to replicate the issue you described. Please test https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/download/latest/ZuluSCSI_RP2040_2023-03-24_b4406c6.bin which should work properly.

**Comment by chickeneps** [comment]
Confirmed fixed, thank you!

**Comment by chickeneps** [comment]
You may know this already, and I think I made a mistake, but this problem extends to the full-size as well. Pi-Day release RP2040 all affected. I assume that the fix above fixes full-size as well, since it's the same firmware.

**Comment by chickeneps** [comment]
I'm sorry, now that I'm using my brain again - please understand I don't work with the "blue" boards anymore, aside from keeping a couple in storage for testing. Accidentally, I tried the 3.14 version on a full-size (1.1) board and that crashed.

I edited the issue title to reflect that I think the 3.14 build affected all ZuluSCSI's.

So I think we need  3 new builds; the red one (already done) and a 1.1 one and 1.0 one. (And a BS one, but I don't know what BS is - well, I do, but you know...)

**Comment by aperezbios** [comment]
@chickeneps yes, the fix is the same, for all platforms.

**Comment by MeTalOneOEight** [comment]
> (And a BS one, but I don't know what BS is - well, I do, but you know...)

BS in this board context is short for the BlueSCSIv2 board which shares the code basis.

**Comment by aperezbios** [comment]
@chickeneps this should be fully resolved in the v2023.03.27 release, which was made yesterday. Please download https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/download/v2023.03.27/ZuluSCSI_RP2040_2023-03-27_924d905.bin and verify.

**Comment by chickeneps** [comment]
Tried v2023.03.30 with ID 7 on a number of samplers, works fine, no problems as far as I could see. r27 fixed it too, but I couldn't witness the issues you did/could.

**Comment by aperezbios** [comment]
Fixed as of v2023.03.30

**Comment by chickeneps** [comment]
Thanks you guys, it's a pleasure to know how on top of things you guys are proving to be.
