### ISSUE TITLE
Allow configuring initiator mode from config file

### ISSUE THREAD

**Issue by twistdroach** [ZuluSCSI/ZuluSCSI-firmware#173]
Would be nice to be able to use the RP2040 mini in initiator mode via config file, since it is missing the config switch

**Comment by PetteriAimonen** [comment]
The initiator mode changes hardware operation on electrical level, so on current hardware it cannot be done by software (RP2040 doesn't have enough GPIOs to control everything).

On the mini, initiator mode can be enabled by soldering a 0 ohm resistor or a switch to R320 pads, located 2 cm upwards from the "ZuluSCSI" text. Not very convenient, I admit.

**Comment by twistdroach** [comment]
Totally happy with that - thanks for your help!
