### ISSUE TITLE
Feature: Implement supply voltage monitoring

### ISSUE THREAD

**Issue by PetteriAimonen** [ZuluSCSI/ZuluSCSI-firmware#174]
Sometimes problems have been caused by insufficient power supply through SCSI cable (e.g. #172).

The internal ADC in the microcontroller could be used to detect these situations.
The chips also have brown-out detector, which activates when the voltage falls very low - threshold is probably too low to be useful for this purpose, as SCSI communication is affected earlier than the microcontroller operation.

On RP2040, the temperature sensor outputs a voltage of 0.7 V, from which the VDD voltage level can be calculated.
Same for GD32.

**Comment by aperezbios** [comment]
@PetteriAimonen agreed, this would be a great addition.
