### ISSUE TITLE
Stability issues on Power Mac 9600's internal (FAST SCSI-2) bus

### ISSUE THREAD

**Issue by XodiumRetro** [ZuluSCSI/ZuluSCSI-firmware#18]
I'm having some trouble getting a ZuluSCSI 1.1 working with my Power Mac 9600. Sometimes it'll work insofar as I can get the system to boot, but if I try to copy a file to the image loaded into the ZuluSCSI, it'll lock up midway through (and the ZuluSCSI's access LED will remain solid until it eventually times out, at least I'm assuming that's what is happening.)

It'll also just hang the system at the gray screen, before a happy Mac even has the chance to come up. Though it seems to be chance whether it makes it past this point.

This is on the 9600's internal bus, have tried both the 16GB image I wanted to use and a smaller 4GB image, instability has been observed in both (and both images were created with dd on an M1 MacBook Pro). Both images also work fine in a BlueSCSI/BlueSCSI F4. (I'm using 8.6, by thr way)

I've seen this behavior across two different ZuluSCSIs and two different 9600s (a Tsunami and also a Kansas model, this didn't change anything).

EDIT: Also confirmed (via a friend) that the Power Mac 7300 seems to exhibit the same problem.

The only time I've been able to get a ZuluSCSI fully working on the 9600 is by either using the second bus (the one shared with the external DB-25) or a third party SCSI card (in my case, I have an ATTO ExpressPCI Pro, and it works great there!) And this is both with and without SW1 toggled.

I've also tested it in a LC 475 and it works absolutely flawlessly there.

To make it easy to glance, here's what I've tried that didn't work:

1. Updated to latest stable *and* nightly firmware
2. Tried isolating ZuluSCSI/unplugging all other devices on same bus
3. Tried setting/unsetting SW1
4. Tried turning off termination
5. Tried external berg power
6. Tried in both Tsunami and Kansas boards
7. Tried setting Apple-centric options in ZuluSCSI.ini (before realizing SW1 just does this already, whoops)
8. Tried 2, 4, and 16GB images (that work fine on both an OG and F4 BlueSCSI)
9. And for good measure, tried different SCSI cables and SD cards

The things that DID work:

1. Using 2nd SCSI bus on 9600 (albeit with a speed penalty because slower bus) 
2. Using third party SCSI card (ATTO ExpressPCI Pro)
3. Different machine entirely (LC 475)
4. Disabling synchronous SCSI/setting it to 5 (both worked the same, allowing the ZuluSCSI to work albeit with a sizeable performance hit)

I've enclosed debug logs for every fault I observed (turning off the system and pulling the log after the freeze occurred) and one for a normal boot and file copy from the ATTO card for good measure. If there's anything more needed on my end, or if I missed something, let me know. Thanks!

EDIT 7/15/22: I did some further testing on the advice of someone else and rolled my ZuluSCSI back to 1.0.0 and I can confirm right off that it seems more stable on 1.0. I've been testing it on my PM6500 and it was having the very same stability problems there (even just using it as a storage disk, not boot), but after rolling it back to 1.0 it's been stable and hasn't hung the system yet. I plan to check the 9600 again later. I'll also gradually bring up the firmware and update after I've tried that.

Just to keep it in list form, the Power Macs so far affected by this seem to be:
9600 (and by extension, 9500 since they use similar boards?)
9600 v2 (Kansas/300MHz+ models)
7300
6500 (but works fine when rolled back to 1.0.0)
6100 (was talking about this in a Discord and someone with a 6100 mentioned having similar problems with their Zulu, throwing it in here for good measure)

[Frozen when hitting 7.6 desktop](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/8986227/FrozeAtDesktop.txt)
[Normal, functional boot on ATTO card](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/8986228/FunctionalBootWithATTO.txt)
[Frozen at gray screen](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/8986229/GrayScreenFreeze.txt)
[Frozen in OS, light comes on solid, eventually times out.](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/8986230/SolidLightHang.txt)
[A log of a bunch of attempted 9600 boots](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/8986231/ABunchOfBootFails.txt)

**Comment by aperezbios** [comment]
@XodiumRetro can you try explicitly setting "MaxSyncSpeed = 5" in the [ZuluSCSI] section of zuluscsi.ini? I suspect what's going on here is that the ZuluSCSI and PowerMac may be incorrectly negotiating 10Mbyte/sec synchronous SCSI, and the AM79C950 which contains the SCSI controller in the PM9500/9600 only supports 5MByte/sec synchronous transfers. 

The Apple Network Server, as well as PowerMac 9500/9600, use the CURIO ASIC (AM79C950, custom part from AMD), also used in other PowerMac machines, such as the 7200, to "support serial ports, a slow (5 Mbit/s, 53C94/96 based) SCSI bus and 10Mbit/s ethernet."

**Comment by XodiumRetro** [comment]
@aperezbios Gave it a quick go on my beige G3 minitower (had the machine open for other things and it's the same machine Bruce was using for testing, as far as I know...) 

Setting MaxSyncSpeed to 5 crashes it as if it were set to 10. Setting it to 0 allows the ZuluSCSI to function normally, albeit topping out at 3.3MB/s read and 2.7MB/s write. I'm sure that's easily within spec for 5MB/s SCSI, but having it connected to an external SCSI2 card I was seeing way north of that.

But as you mention, could be a limitation of the inbuilt SCSI controller. I know the service manual for the 9600s state the internal bus *should* top out at 10MB/s and the external bus tops out at 5, and I've seen the internal bus hit well over 5MB/s with spinning rust drives (shocked I was able to find one still working well enough, even). So at this point yeah, the ZuluSCSI works with MaxSysnc set to 0, but on the flip, I'm also wondering if some performance is maybe being left on the table?

(Also, as mentioned, this problem only ever cropped up after 1.0.1. If I downgrade to 1.0.0, The ZuluSCSI can be used out of the box with no issues and no crashes.)

**Comment by XodiumRetro** [comment]
Whoops, did NOT mean to click that button, my bad!

**Comment by aperezbios** [comment]
No worries. Thanks for testing. Sounds like there may be a regression. We'll figure it out.

**Comment by XodiumRetro** [comment]
That's what's interesting to me. I know 1.0.2 brought a LOT of things to the table (including the 4GB image fix) and I fully expected the break to occur just there, but...1.0.1 crashes too, at least on mine and one other ZuluSCSI I know of that a friend has. When I have time I'll do some further testing with the firmwares, but it definitely appears this issue began in 1.0.1 on my end, at least.

**Comment by aperezbios** [comment]
@XodiumRetro on the off chance that this might rectify your situation, I'd like to request that you try with firmware v1.0.3, which was released a day ago.  You can download it from https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/download/v1.0.3/ZuluSCSIv1_1_2022-07-29-v1.0.3.bin

**Comment by XodiumRetro** [comment]
@aperezbios so I'm testing the new firmware as we speak. Good news is that 1.0.3 seems to have improved things insofar as the lockups don't occur pre-boot anymore. I've done a few boot cycles with the beige G3 and I can consistently hit desktop and actually use the system without the ZuluSCSI locking up the system.

However trying to boot from the Zulu itself is still a bit problematic, it's freezing halfway through an OS 9.2.2 boot, and file copies sometimes work, sometimes end in a crash (solid light on Zulu, system freeze, then it goes out as if it has given up). Setting MaxSyncSpeed to 5 still procs a crash, MaxSyncSpeed 0 allows the boot to proceed normally but with a performance hit (3.1MB/s vs. 4.2MB/s read, write still stayed around 2.2-2.5MB/s)

I've attached debug logs both with SW1 off and on. This is out of the box, no zuluscsi.ini set at this point. 
[Failed9Boot SW1 On.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9223893/Failed9Boot.SW1.On.txt)
[Failed 9 Boot SW1 Off.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9223894/Failed.9.Boot.SW1.Off.txt)

I do know Garth Beagle is testing alongside me and is saying that at least on his 9600 (mine's kinda in stasis for VCF West) the problem seems to show no improvement. I did ask him to comment in this thread so you can hear from him directly, however. I just know we've been comparing notes and such as this is ongoing.

**Comment by aperezbios** [comment]
@XodiumRetro if you're getting the solid light, please wait 30-35 seconds, as, the hardware watchdog may have triggered. If you could attempt booting with debug enabled, a debug log would also be helpful.

**Comment by XodiumRetro** [comment]
@aperezbios I'll try again just to make 100% sure I've given it time, but usually given how long the beige G3 takes to SCSI boot I'll set it on its way and go grab a drink or something. The above logs I attached are with the debug switch set. I've got errands to do as of now so I'll have to get around to it later tonight. If the light going out after it being solid for a while indicates the hardware watchdog has done its thing, then that's what I was seeing. (I waited until the light went out.)

Though now that you mention that, the initial logs (I sent a screenshot to Bruce some time ago) ended in WATCHDOG_TIMEOUT. If that's relevant.

Garth is working on getting his on GH account and commenting directly here, but talking with him he seems to have uncovered a weird failure mode: He says in his tests the images are actually getting corrupted when the crash occurs. Which is odd because that's not the behavior I'm seeing on the G3. Asking him if he can provide his logfiles and I'll update when he can get them.

**Comment by garthbeagle** [comment]
@aperezbios Yes I can confirm the issue still occurs with 1.0.3 FW on 9600.

The drive corruption may just be a red herring, but it is a different behaviour - in the past 1.5hrs of testing, when it's failed it has a few times put the image into some sort of state where it won't boot at all (sits at grey screen with blinking "missing OS" folder) on either the failing setup or a setup that does not produce the bug (eg: LC475 or using the image in Basilisk II) - does not matter if debug logging is set either. Somehow then the image will start working again, I'm not 100% sure how. This is definitely not something I've seen before, and I've done considerable testing around this bug.

Here are logs from booting with debug enabled, the first is from a boot where it just hung (at grey screen/Happy Mac) and the 2nd is the same hang behaviour but produced the wonky image issue (I'm guessing the log appends? so really the 2nd log may include both)

[zululog-fail1.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9224018/zululog-fail1.txt)
[zululog-fail2.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9224019/zululog-fail2.txt)

(I waited about 45 seconds after the yellow light went off on the card before killing power to make sure it'd written out what it was going to write)

**Comment by garthbeagle** [comment]
Confirmed issue still occurs with the 1.0.5 (ZuluSCSIv1_1_2022-08-12-v1.0.5.bin) beta firmware. Debug log:
[zululog-fail.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9364201/zululog-fail.txt)

I tested on a 9600, first confirmed I could boot ok with ZuluSCSI connected to the int/ext SCSI port (the one furthest from the edge of the logic board) and that it flashed. Then connected it to the int SCSI port (the one closest to the edge of the logic board) and it failed 2/2 boots, locked at the grey screen Happy Mac icon.

**Comment by aperezbios** [comment]
@garthbeagle with 1.0.4/1.0.5, you'll need to test with PrefetchBytes=0 set in the [SCSI] section of your zuluscsi.ini file. With prefetch enabled, it should work properly.

**Comment by garthbeagle** [comment]
@aperezbios still hangs with PrefetchBytes=0 set, same setup as noted above. The log (which this time when it hung the yellow LED never went off, I waited about 2 minutes after it hung before pulling power) 
[zululog2.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9364907/zululog2.txt)

@aperezbios have you been able to reproduce this yourself?

**Comment by aperezbios** [comment]
@garthbeagle try with https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/download/latest/ZuluSCSIv1_1_2022-08-17_a1c1100.bin

**Comment by garthbeagle** [comment]
@aperezbios I can try it when I have a chance - what were the changes?  And were you able to reproduce the issue?

I'm certainly willing to help here to get this fixed if you don't have the right setup to reproduce this.

**Comment by garthbeagle** [comment]
@aperezbios I tested ZuluSCSIv1_1_2022-08-17_a1c1100.bin on the 9600. I first confirmed it booted ok off the SCSI port that does not have the issue. I then tried it off the SCSI port where it fails, and it still fails - locks at grey screen / Happy Mac during boot, log:
[zululog4.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9366051/zululog4.txt)

Incidentally, the hda image also was corrupted, I was no longer able to boot off it (would briefly show Happy Mac, then flashing empty folder) including off either the failing or working SCSI port. I'd previously intermittently hit this behaviour (see my comments from 19 days ago)

At this point, I'm not likely to try any other changes unless I can get some more information from you as to what the changes are that you're asking us to try and why they'll help address this. Again, I'm willing to assist if you do not have the hardware to reproduce or if you are having issues reproducing (which ideally would mean we'd just need to give you the correct information to help) but am not willing to simply just blindly try changes.

**Comment by aperezbios** [comment]
@garthbeagle thanks for the log. While it may seem like we're not making any progress from your perspective, I can assure you that we are, and things have been improving for @XodiumRetro in his testing. 

The logfile above shows a watchdog timeout, which we'll look in to. 

`[62593ms] DBG ---- DATA_IN, syncOffset 15 syncPeriod 25
[77591ms] WATCHDOG TIMEOUT at PC 0x08012B7A LR 0x00009CF8 attempting bus reset
[77600ms] DBG ---- Total IN: 26112 OUT: 0 CHECKSUM: 45192
[77600ms] SCSI ID 0 negotiated synchronous mode 4 MB/s (period 4x61 ns, offset 133 bytes)`

Can you try setting MaxSyncSpeed=0 in your zuluscsi.ini? This will disable synchronous SCSI negotiation completely, and may result in stable operation for you. It's not a fix, but a way of testing/validating that this is a problem that's specific to Synchronous SCSI mode.

**Comment by XodiumRetro** [comment]
So I've been troubleshooting this with @aperezbios in DMs and can confirm that at least for me things are improving, at least testing with 1GB HFS images so far. Even with PrefetchBytes set to 8192, oddly enough. Going to do more experimenting with larger images and HFS+ to see if that somehow changes things, but things are looking more promising, at least.

I have the ZuluSCSI sitting on the internal SCSI bus by itself (to isolate anything else messing with it) with a fresh SD card and firmware 1.0.5.

Though I am noticing the seek times are looking a bit odd (usually get 0.25ms or so, but am now seeing 5ms+. Doing more experimenting to double check everything). Still, at least on my end, crashes are a lot more rare as of now.

**Comment by garthbeagle** [comment]
@aperezbios with both MaxSyncSpeed=0 and PrefetchBytes=0 set, it's stable. I was able to do a about 5-6 cold/warm boots ok. 

I'm sure this is expected, but the mouse cursor is terribly jumpy (as if there's a large load on the system) whenever there is disk activity.

Log (if you need it)
[zululog5.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9366355/zululog5.txt)

**Comment by aperezbios** [comment]
@garthbeagle Thank you for this log. That's at least what I would have expected, switching back to async mode. Now, if you could try with PhyMode=2 and PrefetchBytes=0, and remove MaxSyncSpeed=0 , I'd like to see if that's stable for you. Assuming it is, you could also try PhyMode=3.

**Comment by garthbeagle** [comment]
@aperezbios with PrefetchBytes = 0 and PhyMode = 2 (and MaxSyncSpeed=0 removed) it hangs on boot (grey screen / Happy Mac, yellow LED stayed on for a bit, then shut off) - here's the log
[zululog6.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/9374760/zululog6.txt)

**Comment by aperezbios** [comment]
@garthbeagle and @XodiumRetro, I believe we finally have this bug squashed. Please comment out all zuluscsi.ini global settings, and test with this 1.0.6-rc2 build: https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/download/v1.0.6-rc2/ZuluSCSIv1_1_2022-08-19_53343f4.bin

Here's what our lead firmware developer @PetteriAimonen wrote about the fix:

> Indeed there was a pretty severe timing violation in the 10 MB/s synchronous mode.
> I had been relying too much on logic analyzer which only shows the timing at one threshold voltage.
> The SCSI spec specifies low as below 0.8V and high as above 2.0V.
> At high speeds the pulse didn't rise as fast as logic analyzer trace showed.
> The Fast SCSI spec requires pulse width of 30 ns, while it was just 15 ns above the 2.0V threshold.
> The low pulse was unnecessarily long, so just adjusting the balance I was able to achieve Fast SCSI timings without reducing performance.
> There was even some margin left over to account for longer cables.

**Comment by garthbeagle** [comment]
Yay, for me @aperezbios it does indeed seem to be fixed.

I've done various boots, benchmarks, file copies, installs on my original failing setup (2GB HFS on crummy slow 4GB microSD) and a faster SD (8GB HFS+ on fast 32GB SD) without seeing the reported issue 👍

Yay, thanks!

**Comment by XodiumRetro** [comment]
Alright, so I think this is as good as done. Garth mentioned another bug that @aperezbios is thankfully aware of and working on with Disk Utility being kinda weird.

And I can say whatever @PetteriAimonen did is magic because now I'm seeing amazing performance across the board along with the ZuluSCSI no longer crashing the 9600. Seeing 7.7MB read and 3.2MB write from the internal bus when previously it was topping out at 4MB or so with sync speed manually set to 5 and Prefetch turned off.

Going to mark this as closed now as the issue this thread was created for is definitely fixed, my own 9600's quirks and features notwithstanding (and no fault of the ZuluSCSI itself).
