### ISSUE TITLE
Print PhyMode in the log file

### ISSUE THREAD

**Issue by tenox7** [ZuluSCSI/ZuluSCSI-firmware#194]
Could ZuluSCSI firmware log what is the current negotiated phy mode for the SD card?

I'm referring to this config line:

```
#PhyMode = 0   # 0: Best available  1: PIO  2: DMA_TIMER  3: GREENPAK_PIO   4: GREENPAK_DMA
```

In case of 0 "Best available" it would be awesome to see what has been negotiated. 

Thanks

**Comment by PetteriAimonen** [comment]
The PhyMode only affects GD32 platform. On it it will be printed as line such as:

    SCSI PHY operating mode: GREENPAK_DMA

**Comment by aperezbios** [comment]
@tenox7 as Petteri mentioned, PhyMode is a platform-specific setting, and as of today, it only applies to ZuluSCSI V1.1. 

In f9a328a, I've gone ahead and improved the messaging in the comments of the example zuluscsi.ini file.

**Comment by tenox7** [comment]
awe thanks so much!
