### ISSUE TITLE
Feature request: reduced INI editing when adding CD images

### ISSUE THREAD

**Issue by saybur** [ZuluSCSI/ZuluSCSI-firmware#218]
The current image system requires either renaming CD images to match the auto-scan format (CD3.bin/CD3.cue), _or_ manually typing the name in the INI file. It would be nice if this could be supplemented by scanning a directory on startup. For example:

```
[SCSI3]
Directory = "/cds"
```

Or even better, if a folder named "CD3" is present, a CD-ROM drive gets auto-configured as if each file within the folder had been listed in the INI file using the `IMG` syntax.

Ideally this would use something intuitive to determine the first image mounted: alphabetical ordering would be great if that doesn't add too much complexity.

**Comment by PetteriAimonen** [comment]
Sounds reasonable.

Implementation needs a bit of thought.

The ini file option is simpler to implement and can be done in `scsiDiskGetImageNameFromConfig()`. Something like this would work without needing to sort the full filename list. Basically a selection sort:

1. Check if `directory` is set in .ini
2. Initialize `first_name = ""`
3. Iterate for `image_index` times:
    3.1. Initialize `selected_name = NULL`
    3.2. Iterate for each file in directory that has name like CD image (`.iso` and `.bin`, should ignore at least text files and cues):
          3.2.1. If filename is alphabetically after `first_name` and before `selected_name` or `selected_name` is NULL, store it in `selected_name`.
    3.3. For next iteration, set `first_name = selected_name`.
4. At the end, `selected_name` is the Nth filename in alphabetical order.

For the currently supported 10 image names loading the full array to RAM would also be possible and `qsort()` or `std::sort()` could be used to sort them. But CD ejection is not very time critical so a bit of extra looping through the filesystem should work fine.

Currently directories are ignored when searching for images. Adding them automatically would need `scsiDiskOpenHDDImage` to check for directory and then store the directory path in a new variable `img.directory`.
