### ISSUE TITLE
PIO mode works on v1.0 and V1.0 minis but not with v1.1 on three systems tested

### ISSUE THREAD

**Issue by morio** [ZuluSCSI/ZuluSCSI-firmware#245]
This seems to be an issue throughout the firmware history. We tested with versions 1.2.0, 1.1.5, and 23.06.13.

On a Macintosh LC III, PowerMac 8500/150, and a Dual Pentium III running 32bit Fedora server, putting a v1.1 in PIO mode causes an error.
With ZuluSCSI RP2040 in initiator mode it seemed to copy data just fine.

Steps to reproduce:
* Set PhyMode = 1 in zuluscsi.ini
* Boot computer

The computer will boot up until a point and then the activity LED stops

On the LC III it occurs at the Welcome Screen, on the Power Mac before the welcome screen, and on the Linux box it get a segfault immediately after switching to root.

This probably hasn't been encountered by anybody in casual use, because V1.1 never falls back to PIO mode on its own, and instead falls back to the DMA_TIMER PhyMode.  The ZuluSCSI v1.0 and ZuluSCSI v1.0 mini work just fine in PIO mode, which it was originally designed for.

**Comment by PetteriAimonen** [comment]
Looks to be a random read bug introduced in commit bf78bfd39d6f3bf.
Shows up as data corruption within a few iterations of random_tester.py and corrupts a few kilobytes of sector data.

I'll see if I can figure out what is causing it.
