### ISSUE TITLE
Request: Increase number of ‘multi image file’

### ISSUE THREAD

**Issue by guytaylor** [ZuluSCSI/ZuluSCSI-firmware#246]
multiple image files are configured with IMG0..IMG9 allowing a max of 10.
Could this be increased to allow more?
perhaps IMGA..IMGZ could be added, for a total of 36.
or IMG10..IMG99, for a total of 100.

**Comment by PetteriAimonen** [comment]
The `ImgDir` option added in #218 / #229 could work for this:

It seems that it has not been documented, but it should work like this:

<pre>
[SCSI4]
ImgDir = "my_directory"
</pre>

and then you can create `my_directory` and put as many files there as you want. They will be used in alphabetical order.

**Comment by guytaylor** [comment]
Great, thanks that seems perfect :)
