### ISSUE TITLE
23.10.20-release: New Problem with ISO image

### ISSUE THREAD

**Issue by ufkel** [ZuluSCSI/ZuluSCSI-firmware#325]
Introduced with 23.10.20, there is a new problem regarding the ISO image handling.

What happens:
A bootable ISO image no longer gets mounted. Instead, it "does not appear to be a valid Macintosh disk image". With the previous firmware, it gets mounted OK.

**23.10.20:**
<img width="620" alt="Screenshot 2023-10-26 at 11 26 27" src="https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/68097348/31da0398-d010-4204-822f-21137428a2c2">

**23.09.06:**
<img width="666" alt="Screenshot 2023-10-27 at 08 59 24" src="https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/68097348/f3ee25cb-d206-450e-8dd9-ff4e320b2274">

**Gut feeling:**
The new Macintosh sanity checks are mislead because it is a bootable CDROM with a driver, although the block size is >512. Just a feeling.

**Comment by ufkel** [comment]
For completeness – in 2023.10.26, the problem persists:

**2023.10.26:**
<img width="620" alt="Screenshot 2023-10-27 at 09 29 17" src="https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/68097348/a52fbaf6-bf3a-429b-bf98-1ebfb787f81f">

**Comment by ufkel** [comment]
Even with `DisableMacSanityCheck = 1`, the problem persists.

2023.10.26:
<img width="585" alt="Screenshot 2023-10-29 at 11 35 43" src="https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/68097348/79b1cd3f-f112-48a9-9996-56fe8d48124a">

The ISO image gets wrongly configured as a disk drive, see the red arrow in the log file above and the red rectangle in the screen shot below.
![IMG_6857](https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/68097348/8e3ddefc-a9a5-49f8-af53-795624c839c7)

With 2023.09.06, everything works OK. The ISO image gets configured as a CDROM drive.

**Comment by morio** [comment]
Hi @ufkel 
Hopefully this build fixes the issue 
https://github.com/ZuluSCSI/ZuluSCSI-firmware/actions/runs/6697222030

**Comment by ufkel** [comment]
Hi @morio

Yes, now it does work again - hurray!

Thank you for looking into it.

<img width="585" alt="Screenshot 2023-10-31 at 06 52 48" src="https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/68097348/f7894ab0-668e-44f0-8b59-d8ba14395474">

**Comment by aperezbios** [comment]
The fix for this has been included in the [v2023.10.31](https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/tag/v2023.10.31) release, made earlier today. Closing as fixed.
