### ISSUE TITLE
Support unusual sector sizes

### ISSUE THREAD

**Issue by wohali** [ZuluSCSI/ZuluSCSI-firmware#338]
Symbolics Lisp machines require an unusual disk sector size: 1280 bytes.

Currently the firmware [does not support this](https://github.com/ZuluSCSI/ZuluSCSI-firmware/blob/ec9257cc9dee1240c7a1555c1ef89b5e2953bfb8/src/ZuluSCSI.cpp#L459-L467).

Can support be added for unusual sector sizes please? Otherwise, the device is not usable in these machines.

**Comment by aperezbios** [comment]
@wohali here's a build for you to test whenever you have some time
[ZuluSCSI-firmware-arbitrary-block-sizes-test.zip](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14657657/ZuluSCSI-firmware-arbitrary-block-sizes-test.zip)

**Comment by wohali** [comment]
Thanks @aperezbios this looks to resolve the issue.
