### ISSUE TITLE
Issue: Release ZuluSCSI firmware v2023.11.22 breaks implicit device typing

### ISSUE THREAD

**Issue by ZigZagJoe** [ZuluSCSI/ZuluSCSI-firmware#340]
**Issue**: 

All devices are getting initialized with info for fixed drives. Implicit device types - such as a file named NE0.bin is a network device - are only determined later. The drive info strings need to be updated with any drive type info found while scanning for images.

I specifically had this issue with network devices, seems likely the same applies to other image types (ie. CDs).

**Replication:**

- Create NE0.bin
- Boot system. 
- Find SCSI ID #0 info strings reported with the contents of DRIVEINFO_FIXED
- Dayna functionality does not work due to incorrect device info

This is only an issue with the 11-22 release - 10-31 is OK. Suspect is related to 7f4104c.

Screenshot before I added quirks=1 to the zuluscsi.ini
![PXL_20231125_020530847](https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/202568/92ff01b6-6d8a-4cda-8d9c-9f934ee3c568)

the zululog is from a build i was using to diagnose. Only change is to make setDefaultDriveInfo report what settings it is initializing with. Issue occurs with the official builds.  
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/13462918/zululog.txt)

[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/13462923/zuluscsi.ini.txt)

![2023-11-24 21_07_53-TINYSCSI (G_)](https://github.com/ZuluSCSI/ZuluSCSI-firmware/assets/202568/2d4f76a7-5b73-4f77-b1ce-30a8fb655247)

**Comment by aperezbios** [comment]
@ZigZagJoe thanks, as of last night I un-flagged the v2023.11.22 release as latest, and users should continue to use the previous [v2023.10.31](https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/tag/v2023.10.31) until then. We expeect to have the problem resolved no later than Monday morning.

**Comment by morio** [comment]
Thanks for the find @ZigZagJoe 
Here is an attempt at a fix
https://github.com/ZuluSCSI/ZuluSCSI-firmware/actions/runs/7012142248
Could you see if it resolves your issue?

**Comment by ZigZagJoe** [comment]
> Thanks for the find @ZigZagJoe Here is an attempt at a fix https://github.com/ZuluSCSI/ZuluSCSI-firmware/actions/runs/7012142248 Could you see if it resolves your issue?

Yes, looks good. I just gave it a whirl and I see the expected device info strings for both CD-ROM and network device types. CD-Rom mounts, Dayna driver recognizes the network device and network functionality works too.

**Comment by aperezbios** [comment]
This has been fixed with the [v2023.11.27](https://github.com/ZuluSCSI/ZuluSCSI-firmware/releases/tag/v2023.11.27) release
