### ISSUE TITLE
How to turn on "initiator" mode on "Rev 2022a" Compact RP2040

### ISSUE THREAD

**Issue by mpryon** [ZuluSCSI/ZuluSCSI-firmware#377]
Sorry if it's mentioned, I've looked and looked but cannot figure out how to enable initiator mode on my ZuluSCSI Compact RP2040 Rev 2022a.

**Comment by aperezbios** [comment]
@mpryon the first ZuluSCSI Compact hardware design (rev 2022a) does not support initiator mode. Since you also e-mailed us about this, I'm going to go ahead and close this issue for now, and we can continue to converse via the e-mail thread you started earlier.
