### ISSUE TITLE
Zuluscsi V1.2 in X68000 XVI SCSI Model hangs

### ISSUE THREAD

**Issue by ymos168** [ZuluSCSI/ZuluSCSI-firmware#394]
I have a ZS V1.2 on the latest firmware installed in a X68000 XVI. It hangs with Watchdog Timeouts. Also, for Some reason it looks like Im not able to EnableParity according to the log even tho I enable it in the .ini. Any help is much appreciated.

4GB card with single .hda image

[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14571395/zululog.txt)

[zuluscsiini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14571463/zuluscsiini.txt)

8GB card with multiple .hda images

[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14571420/zululog.txt)

[zuluscsiini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14571460/zuluscsiini.txt)

**Comment by aperezbios** [comment]
@ymos168  thanks for the report, and the debug logs, without having to ask for them :) This comment is simply to acknowledge your report, and let you know we're looking in to the root cause.

**Comment by aperezbios** [comment]
@ymos168 can you try setting System = X68000 in your ini file, and let us know if this changes any behavior? I suspect it will.

 Also, all of the commented out lines have no effect, so the presence of your existing ini file has no effect, and is equivalent to there being no INI file at all.

**Comment by ymos168** [comment]
@aperezbios 

Test With System = X68000
4GB Panasonic SDHC
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588740/zululog.txt)
[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588752/zuluscsi.ini.txt)

8GB Sandisk SDHC
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588760/zululog.txt)
[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588761/zuluscsi.ini.txt)

8GB Sandisk Ulltra
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588785/zululog.txt)
[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588787/zuluscsi.ini.txt)

Test with just  EnableSCSI2 and EnableParity

4GB Panasonic SDHC
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588855/zululog.txt)
[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588858/zuluscsi.ini.txt)

8GB Sandisk SDHC
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588860/zululog.txt)
[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588862/zuluscsi.ini.txt)

8GB Sandisk Ultra
[zululog.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588872/zululog.txt)
[zuluscsi.ini.txt](https://github.com/ZuluSCSI/ZuluSCSI-firmware/files/14588875/zuluscsi.ini.txt)

**Comment by ymos168** [comment]
I gave up on this one and replaced it with ZuluSCSI RP2040. I still have a issue but looks like the log is producing usable data. If there's something wrong with my machine maybe the logs can help. i will close this and open a new thread for the ZuluSCSI RP2040. thanks
