### ISSUE TITLE
Stock Drive Utility sees volume as unsupported device if both SW1 is on AND drive ID info is present in ini

### ISSUE THREAD

**Issue by garthbeagle** [ZuluSCSI/ZuluSCSI-firmware#42]
To reproduce:
0) Power Macintosh 9600/350, ZuluSCSI 1.1 with 1.0.6-rc2 FW connected to Int SCSI bus, at end of chain along with CD and Zip drives, Term and SW1 switches set on.
1. Format SD card as ExFAT / MBR and copy a blank disk image onto it (I used a blank 8192MB image created with https://bluescsi.onegeekarmy.eu/diskjockey/)
2. Copy a zuluscsi.ini file to the SD card, comment all options out except for the vendor, product, version, serial lines
3. Set SW1 on ZuluSCSI to on
4. Boot 9600 off Mac OS 8.6 CD (you can use this copy of 8.6 here https://mega.nz/folder/8hA3AQCJ#pWUq92L70yDXlogy9lk5Dg/folder/ll4HCQQB).
5. Run Drive Setup (1.7.2) off the 8.6 CD.
6. Select your volume to initialize.

Results:
Drive Setup reports the volume as an unsupported drive and will not allow you to initialize it. 

Does not occur if you have only SW1 on or the 4 lines in the ini, not both. My understanding is the ini should override the dip switches.

**Comment by aperezbios** [comment]
@garthbeagle thanks for the report. I tested this, and if you set "RightAlignStrings=0" in your zuluscsi.ini (with SW1 on) it should placate Disk Utility. We will probably disable RightAlignStrings being on by default in the next firmware release, but it requires further testing with HD SC Setup as well.

**Comment by PetteriAimonen** [comment]
I wonder what platforms RightAlignStrings is actually necessary for.
It originated from discussion in private repo issue rabbitholecomputing/ZuluSCSI-firmware#34
I haven't done any testing myself regarding it.

**Comment by aperezbios** [comment]
@garthbeagle After doing some testing, we've gone ahead and disabled right-aligned device/vendor strings by default, when Apple quirks mode is set (either via SW1 on ZuluSCSI V1.0/V1.1, or set explicitly in the INI file with RightAlignStrings=1

93a200, dd103e should put this to bed, and improve compatibility with Drive Setup immensely.
cb92ac also fixes the device/vendor strings so Apple's un-patched CD-ROM extension works properly.

This isn't in a released version of the firmware yet, but it can be tested by downloading the "latest" development build.
