### ISSUE TITLE
RP2040 Initiator mode improvements

### ISSUE THREAD

**Issue by aperezbios** [ZuluSCSI/ZuluSCSI-firmware#77]
@PetteriAimonen Currently, creating image dumps always results in files named "HDx_imaged.hda" regardless of the source media type. I've been able to successfully dump a CD-ROM image. The resulting file should be named according to the device type. CD-ROM images should probably also have .iso suffixes, regardless of whether or not it's actually an ISO filesystem on-disc.

**Comment by PetteriAimonen** [comment]
Implemented in initiator_compatibility_fixes branch commit e4ff824.
